import uniqid from "uniqid";

const leagueChampions = [
	{ name: "Dr. Mundo", suffix: "_0" },
	{ name: "Annie" },
	{ name: "Olaf" },
	{ name: "Galio" },
	{ name: "Twisted Fate" },
	{ name: "Xin Zhao" },
	{ name: "Urgot" },
	{ name: "LeBlanc" },
	{ name: "Vladimir" },
	{ name: "Fiddlesticks" },
	{ name: "Kayle" },
	{ name: "Master Yi" },
	{ name: "Alistar" },
	{ name: "Ryze" },
	{ name: "Sion" },
	{ name: "Sivir", suffix: "_0" },
	{ name: "Soraka" },
	{ name: "Teemo" },
	{ name: "Tristana" },
	{ name: "Warwick" },
	{ name: "Nunu & Willump" },
	{ name: "Miss Fortune" },
	{ name: "Ashe" },
	{ name: "Tryndamere" },
	{ name: "Jax", suffix: "_0" },
	{ name: "Morgana" },
	{ name: "Zilean" },
	{ name: "Singed" },
	{ name: "Evelynn" },
	{ name: "Twitch" },
	{ name: "Karthus" },
	{ name: "Cho'Gath" },
	{ name: "Amumu" },
	{ name: "Rammus" },
	{ name: "Anivia" },
	{ name: "Shaco" },
	{ name: "Sona" },
	{ name: "Kassadin", suffix: "_0" },
	{ name: "Irelia" },
	{ name: "Janna" },
	{ name: "Gangplank" },
	{ name: "Corki" },
	{ name: "Karma" },
	{ name: "Taric" },
	{ name: "Veigar" },
	{ name: "Trundle" },
	{ name: "Swain" },
	{ name: "Caitlyn" },
	{ name: "Blitzcrank" },
	{ name: "Malphite" },
	{ name: "Katarina" },
	{ name: "Nocturne" },
	{ name: "Maokai" },
	{ name: "Renekton" },
	{ name: "Jarvan IV" },
	{ name: "Elise" },
	{ name: "Orianna" },
	{ name: "Monkey King" },
	{ name: "Brand" },
	{ name: "Lee Sin", suffix: "_0.leblanc_rework" },
	{ name: "Vayne" },
	{ name: "Rumble" },
	{ name: "Cassiopeia" },
	{ name: "Skarner", suffix: "_0" },
	{ name: "Heimerdinger" },
	{ name: "Nasus" },
	{ name: "Nidalee" },
	{ name: "Udyr" },
	{ name: "Poppy" },
	{ name: "Gragas" },
	{ name: "Pantheon" },
	{ name: "Ezreal" },
	{ name: "Mordekaiser" },
	{ name: "Yorick" },
	{ name: "Akali" },
	{ name: "Kennen" },
	{ name: "Garen" },
	{ name: "Leona" },
	{ name: "Malzahar" },
	{ name: "Talon" },
	{ name: "Riven" },
	{ name: "Kog'Maw" },
	{ name: "Shen" },
	{ name: "Lux" },
	{ name: "Xerath" },
	{ name: "Shyvana" },
	{ name: "Ahri", suffix: "_0" },
	{ name: "Graves" },
	{ name: "Fizz" },
	{ name: "Volibear" },
	{ name: "Rengar" },
	{ name: "Varus" },
	{ name: "Nautilus" },
	{ name: "Viktor", suffix: "_0.viktorvgu" },
	{ name: "Sejuani" },
	{ name: "Fiora" },
	{ name: "Ziggs" },
	{ name: "Lulu" },
	{ name: "Draven" },
	{ name: "Hecarim", suffix: "_0" },
	{ name: "Kha'Zix" },
	{ name: "Darius" },
	{ name: "Jayce" },
	{ name: "Lissandra" },
	{ name: "Diana" },
	{ name: "Quinn" },
	{ name: "Syndra", suffix: "_0" },
	{ name: "Aurelion Sol" },
	{ name: "Kayn" },
	{ name: "Zoe" },
	{ name: "Zyra" },
	{ name: "Kai'Sa" },
	{ name: "Seraphine" },
	{ name: "Gnar" },
	{ name: "Zac" },
	{ name: "Yasuo" },
	{ name: "Vel'Koz" },
	{ name: "Taliyah" },
	{ name: "Camille" },
	{ name: "Akshan" },
	{ name: "Bel'Veth" },
	{ name: "Braum" },
	{ name: "Jhin" },
	{ name: "Kindred" },
	{ name: "Zeri", suffix: "_0" },
	{ name: "Jinx" },
	{ name: "Tahm Kench" },
	{ name: "Viego" },
	{ name: "Senna" },
	{ name: "Lucian" },
	{ name: "Zed" },
	{ name: "Kled" },
	{ name: "Ekko" },
	{ name: "Qiyana" },
	{ name: "Vi" },
	{ name: "Aatrox" },
	{ name: "Nami" },
	{ name: "Azir" },
	{ name: "Yuumi" },
	{ name: "Samira" },
	{ name: "Thresh" },
	{ name: "Illaoi" },
	{ name: "Rek'Sai" },
	{ name: "Ivern" },
	{ name: "Kalista" },
	{ name: "Bard" },
	{ name: "Rakan" },
	{ name: "Xayah" },
	{ name: "Ornn" },
	{ name: "Sylas" },
	{ name: "Neeko" },
	{ name: "Aphelios" },
	{ name: "Rell" },
	{ name: "Pyke" },
	{ name: "Vex" },
	{ name: "Yone" },
	{ name: "Sett" },
	{ name: "Lillia" },
	{ name: "Gwen", suffix: "_0" },
	{ name: "Renata" },
	{ name: "Nilah" },
	{ name: "K'Sante" },
	{ name: "Milio", suffix: "_0" },
	{ name: "Naafiri", suffix: "_0" },
];

const gameCards: GameCard[] = leagueChampions.map(({ name, suffix }) => {
	const id = name.toLowerCase().replace(/[^A-Za-z]/g, "");
	const image = `https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/assets/characters/${id}/skins/base/${id}loadscreen${suffix || ""}.jpg`;

	return {
		name,
		id,
		image,
	};
});

export default gameCards;
