name: Build and deploy static content to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy Static HTML Project Files
        run: |
          rm -rf dist && mkdir -p dist
          cp README.md ./dist/
          cp -r html\&css/* ./dist/
          cp -r js/tic-tac-new ./dist/
          cp -r js/calculator ./dist/
          cp -r js/etch-a-sketch ./dist/
          cp -r js/library-new ./dist/library
          cp -r js/rock-paper-scissors ./dist/
          cp -r js/google-home ./dist/
      - name: Build Battleship
        run: |
          cd js/battleship && npm install && npm run build
          cp -r dist ../../dist/battleship
      - name: Build Todo List
        run: |
          cd js/to-do-remake && npm install && npm run build
          cp -r dist ../../dist/to-do-list
      - name: Build Restaurant
        run: |
          cd js/restaurant && npm install && npm run build 
          cp -r dist ../../dist/restaurant
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./dist
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
